### ISSUE TITLE
Disable the default clusterSPIFFEID

### ISSUE THREAD

**Issue by markgoddard** [cofide/cofidectl#92]
If you create a trust zone with no attestation policies bound to it, we currently enable the default clusterSPIFFEID. This resource matches any pod in a non-spire namespace:

```yaml
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - spire
      - spire-server
      - spire-system
  spiffeIDTemplate: spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{
    .PodSpec.ServiceAccountName }}
```

This behaviour is surprising, and we should instead rely on an explicit catch-all attestation policy being bound to the trust zone:

```
cofidectl attestation-policy add kubernetes --name catch-all
```
